name: Azure Static Web Apps CI/CD

pr:
  branches:
    include:
      - copilot-metrics-viewer

trigger:
  branches:
    include:
      - copilot-metrics-viewer

jobs:
- job: build_and_deploy_job
  displayName: Build and Deploy Job
  condition: or(eq(variables['Build.Reason'], 'Manual'),or(eq(variables['Build.Reason'], 'PullRequest'),eq(variables['Build.Reason'], 'IndividualCI')))
  pool:
    vmImage: ubuntu-latest
  variables:
  - group: Azure-Static-Web-Apps-orange-hill-0d26fee1e-variable-group
  steps:
  - checkout: self
    submodules: true

  - task: NodeTool@0
    displayName: 'Install Node.js'
    inputs:
      versionSpec: '22.13.1'

  - script: |
      npm install
    displayName: 'npm install'

  #- script: |
  #    npm run start
  #  displayName: 'npm start'

  - script: |
      npm run build
    displayName: 'npm run build'

  - task: AzureStaticWebApp@0
    inputs:
      azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_API_TOKEN_ORANGE_HILL_0D26FEE1E)
###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
# For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
      app_location: "/" # App source code path
      api_location: ".output/server" # Api source code path - optional
      output_location: ".output/public" # Built app content directory - optional
###### End of Repository/Build Configurations ###d###

